"""le-vibe: hardware-aware local Ollama model setup for Continue + Code - OSS (Lé Vibe)."""

from .api import EnsureBootstrapArgs, ensure_bootstrap, print_final_instructions
from .first_run import ensure_product_first_run, first_run_marker_path
from .managed_ollama import (
    ManagedOllamaState,
    ensure_managed_ollama,
    stop_managed_ollama,
)
from .paths import LE_VIBE_MANAGED_OLLAMA_PORT, le_vibe_config_dir
from .reporting import LOCKED_MODEL_FILENAME
from .continue_workspace import (
    LVIBE_CONTINUE_RULE_NAME,
    PRODUCT_WELCOME_RULE_NAME,
    ensure_continue_lvibe_rules,
)
from .editor_welcome import WELCOME_MD_NAME, ensure_lvibe_welcome_md
from .session_orchestrator import (
    apply_opening_skip,
    ci_evidence_summary,
    evaluate_stop_condition,
    evidence_artifact_registry,
    evidence_artifact_session_map,
    evidence_provenance_report,
    ensure_pm_session_artifacts,
    failure_mode_catalog,
    final_milestone_lock_criteria,
    get_milestone_by_id,
    get_product_milestones,
    goal_alignment_checks,
    iter_tasks_in_epic_order,
    load_session_manifest,
    milestone_dependency_visibility,
    milestone_definition_of_done_checks,
    progress_confidence_report,
    persist_goal_alignment_check,
    persist_remaining_gaps_report,
    persist_release_readiness_summary,
    persist_stop_condition_check,
    parse_ci_failure_evidence,
    remaining_gaps_report,
    release_readiness_summary,
    resolve_next_step_after_opening_skip,
    session_manifest_example_source_path,
    stop_condition_check,
    upsert_goal_alignment_check,
    upsert_final_milestone_lock_criteria,
    upsert_failure_mode_catalog,
    upsert_milestone_dependency_visibility,
    upsert_milestone_definition_of_done_checks,
    upsert_progress_confidence_report,
    upsert_remaining_gaps_report,
    upsert_release_readiness_summary,
    upsert_stop_condition_check,
    upsert_ci_evidence_summary,
)
from .welcome import maybe_print_welcome, welcome_marker_path
from .workspace_hub import (
    ensure_gitignore_has_lvibe,
    ensure_lvibe_workspace,
    prepare_workspaces_for_editor_args,
    workspace_roots_from_editor_args,
)

__version__ = "1.0.0"

__all__ = [
    "EnsureBootstrapArgs",
    "LE_VIBE_MANAGED_OLLAMA_PORT",
    "LOCKED_MODEL_FILENAME",
    "LVIBE_CONTINUE_RULE_NAME",
    "PRODUCT_WELCOME_RULE_NAME",
    "WELCOME_MD_NAME",
    "ManagedOllamaState",
    "apply_opening_skip",
    "ci_evidence_summary",
    "ensure_continue_lvibe_rules",
    "ensure_lvibe_welcome_md",
    "ensure_bootstrap",
    "evaluate_stop_condition",
    "evidence_artifact_registry",
    "evidence_artifact_session_map",
    "evidence_provenance_report",
    "failure_mode_catalog",
    "final_milestone_lock_criteria",
    "ensure_gitignore_has_lvibe",
    "ensure_lvibe_workspace",
    "ensure_managed_ollama",
    "ensure_pm_session_artifacts",
    "ensure_product_first_run",
    "first_run_marker_path",
    "get_milestone_by_id",
    "get_product_milestones",
    "goal_alignment_checks",
    "iter_tasks_in_epic_order",
    "le_vibe_config_dir",
    "load_session_manifest",
    "milestone_dependency_visibility",
    "milestone_definition_of_done_checks",
    "progress_confidence_report",
    "maybe_print_welcome",
    "persist_goal_alignment_check",
    "persist_remaining_gaps_report",
    "persist_release_readiness_summary",
    "persist_stop_condition_check",
    "parse_ci_failure_evidence",
    "remaining_gaps_report",
    "release_readiness_summary",
    "session_manifest_example_source_path",
    "upsert_goal_alignment_check",
    "upsert_ci_evidence_summary",
    "upsert_final_milestone_lock_criteria",
    "upsert_failure_mode_catalog",
    "upsert_milestone_dependency_visibility",
    "upsert_milestone_definition_of_done_checks",
    "upsert_progress_confidence_report",
    "upsert_remaining_gaps_report",
    "upsert_release_readiness_summary",
    "prepare_workspaces_for_editor_args",
    "print_final_instructions",
    "resolve_next_step_after_opening_skip",
    "stop_condition_check",
    "stop_managed_ollama",
    "upsert_stop_condition_check",
    "welcome_marker_path",
    "workspace_roots_from_editor_args",
]
